#! /bin/sh

pgrep sxhkd >/dev/null || sxhkd &
pgrep polybar >/dev/null || polybar -r main &
pgrep nm-applet >/dev/null || nm-applet --sm-disable &
pgrep clipmenud >/dev/null || CM_SELECTIONS=clipboard clipmenud &
nitrogen --restore &

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do 
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

bspc monitor -d 1 2 3 4 5 6 7 8

# default desktop layout to monocole
for i in {1..8}
do
  bspc desktop $i -l monocle
done

bspc config border_width         2
bspc config window_gap           0
bspc config top_padding          18
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc rule -r *:*
bspc rule -a Gimp desktop='^7' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Transmission-gtk state=floating
bspc rule -a Steam desktop='^6'
bspc rule -a Ncmpcpp desktop='^5'
bspc rule -a Sonata desktop='^5'
bspc rule -a Spotify desktop='^5'
bspc rule -a Pcmanfm desktop='^4'
bspc rule -a Nautilus desktop='^4'
bspc rule -a Ranger desktop='^4'
bspc rule -a Chromium desktop='^2'
bspc rule -a Artha state=floating
